// Generated by CoffeeScript 1.12.7
(function() {
  var CONSOLE_URI, CompositeDisposable, Emitter, Highlights, InkConsole, Point, Range, ref;

  ref = require('atom'), CompositeDisposable = ref.CompositeDisposable, Range = ref.Range, Point = ref.Point, Emitter = ref.Emitter;

  Highlights = require('../highlights.js');

  CONSOLE_URI = 'atom://proto-repl/console';

  module.exports = InkConsole = (function() {
    function InkConsole() {}

    InkConsole.prototype.displayExecutedCode = function(code) {
      var inputCell;
      inputCell = this.console.getInput();
      if (!(inputCell.editor.getText())) {
        inputCell.editor.setText(code);
      }
      this.console.logInput();
      this.console.done();
      return this.console.input();
    };

    return InkConsole;

  })();

}).call(this);
