// Generated by CoffeeScript 1.12.7
(function() {
  var ReplHistory;

  module.exports = ReplHistory = (function() {
    ReplHistory.prototype.history = null;

    ReplHistory.prototype.currentPosition = null;

    function ReplHistory() {
      this.history = [""];
      this.currentPosition = 0;
    }

    ReplHistory.prototype.size = function() {
      return this.history.length;
    };

    ReplHistory.prototype.currentText = function() {
      var text;
      if (text = this.history[this.currentPosition]) {
        return text;
      } else {
        return "";
      }
    };

    ReplHistory.prototype.setCurrentText = function(text) {
      return this.history[this.currentPosition] = text;
    };

    ReplHistory.prototype.setLastTextAndAddNewEntry = function(text) {
      this.history[this.size() - 1] = text;
      if (this.size() >= atom.config.get("proto-repl:historySize")) {
        this.history.shift();
      }
      this.history.push("");
      return this.currentPosition = this.size() - 1;
    };

    ReplHistory.prototype.back = function() {
      if (this.currentPosition > 0) {
        this.currentPosition -= 1;
      }
      return this.history[this.currentPosition];
    };

    ReplHistory.prototype.forward = function() {
      if (this.currentPosition < this.size() - 1) {
        this.currentPosition += 1;
      }
      return this.history[this.currentPosition];
    };

    return ReplHistory;

  })();

}).call(this);
