// Generated by CoffeeScript 1.12.7
(function() {
  var ClojureVersion;

  module.exports = ClojureVersion = (function() {
    ClojureVersion.prototype.major = null;

    ClojureVersion.prototype.minor = null;

    ClojureVersion.prototype.incremental = null;

    ClojureVersion.prototype.qualifier = null;

    function ClojureVersion(versionMap) {
      this.major = Number.parseInt(versionMap.major);
      this.minor = Number.parseInt(versionMap.minor);
      this.incremental = Number.parseInt(versionMap.incremental);
      this.qualifier = versionMap.qualifier;
    }

    ClojureVersion.prototype.isSupportedVersion = function() {
      return this.major === 1 && this.minor >= 6;
    };

    ClojureVersion.prototype.isReaderConditionalSupported = function() {
      return this.minor >= 7;
    };

    return ClojureVersion;

  })();

}).call(this);
