// Generated by CoffeeScript 1.12.7
(function() {
  var Emitter, Repl, Spinner, Task, TreeView, logElapsed, ref, startTime;

  ref = require('atom'), Task = ref.Task, Emitter = ref.Emitter;

  Spinner = require('./load-widget');

  TreeView = require('./tree-view');

  startTime = function() {
    return window.performance.now();
  };

  logElapsed = function(name, start) {
    var elapsed;
    elapsed = window.performance.now() - start;
    return console.log(name + " " + elapsed.toFixed() + " ms");
  };

  module.exports = Repl = (function() {
    Repl.prototype.emitter = null;

    Repl.prototype.process = null;

    Repl.prototype.replView = null;

    Repl.prototype.ink = null;

    Repl.prototype.extensionsFeature = null;

    function Repl(extensionsFeature) {
      this.extensionsFeature = extensionsFeature;
      this.emitter = new Emitter;
      this.loadingIndicator = new Spinner();
    }

    return Repl;

  })();

}).call(this);
